packages:
  - "."
  - "client/*"
  - "server/*"
  - "shared/*"

ignoredBuiltDependencies:
  - '@swc/core'
  - blake-hash
  - bufferutil
  - esbuild
  - protobufjs
  - tiny-secp256k1
  - usb
  - utf-8-validate
